name: Draw-Section-Minimum-Graph

on:
  workflow_dispatch:
    inputs:
      num:
        description: '자연수'
        required: True
        type: string
      sequence_length:
        description: '수열의 항의 개수'
        required: True
        type: string
      section_range:
        description: '구간의 범위'
        required: True
        type: string

run-name: Draw-Section-Minimum-Graph [${{ github.event.inputs.num }}, ${{ github.event.inputs.sequence_length }}, ${{ github.event.inputs.section_range }}]

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: pip install matplotlib
      run: pip install matplotlib
    - name: Run Draw-Section-Minimum-Graph.py
      run: python Draw-Section-Minimum-Graph.py ${{ github.event.inputs.num }} ${{ github.event.inputs.sequence_length }} ${{ github.event.inputs.section_range }}
